my-site/beats/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from beats import views 


urlpatterns = [
    path('home/', views.home, name='home'),
    path('gallery/', views.gallery, name='gallery'),
    path('upload/', views.upload, name='upload'),
    path('history/', views.HistoryNameList.as_view(), name='history'),
    path('beat/<int:pk>/', views.beatdetails, name='beat-details'),
    path('cart/', views.beatcart, name='cart'),
    path('bought/', views.bbought, name='bought'),
    path('buyandcart/<int:pk>/', views.cartbuy, name='buycart'),
    path('cartdetails/', views.cartdetails, name='detailcart'),
    path('cartdelete/<int:pk>', views.cartdelete, name='deletecart'),
    path('listens/<int:pk>', views.listensupdate, name='listensupdate'),
    path('play/', views.playsonng, name='playsong'),
    path('histdetail/<int:pk>', views.historydetail, name='historydetail'),
    path('search/', views.search,name='search'),
    path('beatlist/', views.BeatListView.as_view(), name='beat-list'), 
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my-site/silverchords/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from users import views as users_views
from beats import views as beats_views
from notifis import views as noti_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('galleryouter/', users_views.galleryouter, name='gallery2'),
    path('beats/', include('beats.urls')),
    path('users/', include('users.urls')),
    path('SilverChords/',beats_views.home, name='silverchords'),
    path('help/', users_views.helpinfofun, name='helpinfo'),
    path('notifications/list', include('notifis.urls')),   
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

my-site/users/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from users import views as users_views


urlpatterns = [
    path('register/', users_views.register, name='register'),
    path('profile/', users_views.user_profile, name='profile'),
    path('verification/', users_views.verifi, name='verification'),
    path('editinfo/', users_views.edit, name='editinfo'),
    path('beate/<int:pk>', users_views.editb, name='editbeat'),
    path('notification/<int:pk>', users_views.notif, name='notify'),
    path('advice/', users_views.advice_view, name='advice'),
    path('deleteb/<int:pk>', users_views.deleteb, name='deletebeat'),
    path('userinfo/<int:pk>/', users_views.UserDetailsView.as_view(), name='userinfo'),
    path('login/',auth_views.LoginView.as_view(template_name='users/register.html'), name='login'),    
    path('logout/',users_views.logout_view, name='logout'), 
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my-site/users/models.py
from django.db import models
from django.contrib.auth.models import User

class profile(models.Model):
    user  = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    artist_photo = models.ImageField(default='ap_default.jpg', upload_to='artist_photo')
    cover_photo = models.ImageField(default='cp_default.jpg', upload_to='cover_photo')
    place = models.CharField(max_length=100)
    desc = models.TextField(max_length=2000)
    badge = models.CharField(max_length=20)
    fb = models.CharField(default='facebook.com', max_length=100)
    insta = models.CharField(max_length=100, default='instagram.com')
    youtube = models.CharField(max_length=100, default='youtube.com')
    hashtags = models.CharField(max_length=100, blank=True)
    verified = models.BooleanField(default=False)
    veri_submit = models.BooleanField(default=False)


    def verichange(self):
        self.veri_submit=True
        self.save()

    def __str__(self):
        return f'{self.user.username} Profile'


class quote(models.Model):
    Qid = models.AutoField(primary_key=True)
    data = models.TextField(max_length=1000)

    def __str__(self):
        return f'{self.Qid} quote'

class verification(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    phone = models.CharField(max_length=20, default='000000000000', unique=True)
    email = models.EmailField(unique=True, default='silever@chords.com')
    vtype = models.CharField(max_length=200, default='vtype')
    vno = models.CharField(max_length=100, default='0000000000')
    front_photo = models.ImageField( default='ap_default.jpg', upload_to='verifi_front')
    back_photo = models.ImageField( default='ap_default.jpg', upload_to='verifi_back')

    def __str__(self):
        return f'{self.user.username} Verification'


class helpinfo(models.Model):
    help_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.CharField(max_length=500)

    def __str__(self):
        return self.name

class advice(models.Model):
    a_id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    platform = models.CharField(default='U', max_length=20,choices=[
        ('Y','Youtube'),
        ('I','Instagram'),
        ('F','Facebook'),
        ('S','Snapchat'),
        ('U', 'Us')
        ])
    content = models.TextField(max_length=1000)

    def __str__(self):
        return f'{self.user.username} form'
    
    

my-site/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import profile, verification, advice
from beats.models import work_info

class registerform(UserCreationForm):
    class meta:
        model = User
        fields = ['username', 'password1', 'password2']


class InfoUpdateForm(forms.ModelForm):
    class Meta:
        model = profile
        fields = ['artist_photo', 'cover_photo', 'place', 'desc', 'fb', 'insta', 'youtube']

class BeatUpdateForm(forms.ModelForm):
    class Meta:
        model = work_info
        fields = ['beat_name', 'genre', 'beat_desc', 'price']

class NotifyForm(forms.Form):
    data = forms.CharField(max_length=200, label='data')
    hae = forms.CharField(max_length=200, label='hae')

class helpform(forms.Form):
    name = forms.CharField(max_length=100, label='name')
    email = forms.EmailField(label='email')
    message = forms.CharField(max_length=500, label='message')

class verifiform(forms.ModelForm):
    class Meta:
        model = verification
        fields = ['phone', 'email', 'vtype', 'vno', 'front_photo', 'back_photo']

class adviceform(forms.ModelForm):
    class Meta:
        model = advice
        fields = ['platform', 'content']

my-site/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import registerform, InfoUpdateForm, BeatUpdateForm
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django import forms
from .models import quote, helpinfo, verification, profile, advice
from django.contrib.auth import logout, login
from django.views.generic import DetailView
from django.contrib.auth.models import User
from beats.models import work_info, cart
from notifis.models import notifi
from .forms import NotifyForm, helpform, verifiform, adviceform


def register(request):
    if request.method=='POST':
        form = registerform(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            user = User.objects.filter(username=username)
            login(request, user[0])
            messages.success(request, f'Account Created for {username}!')
            messages.success(request, 'Go to the Edit Info Page and Update your details :)')
            return redirect('editinfo')
        else:
            errors = form.errors
            for error in errors:
                if error[0]=='p':
                    messages.warning(request, "Error in your passsword field")
                elif error[0]=='u':
                    messages.warning(request, "Username already exist")
            return render(request, 'users/register.html')
    else:
        form = registerform()
        return render(request, 'users/register.html')

@login_required
def user_profile(request):
    count=0
    c2 = cart.objects.filter(user_id=request.user.id)
    for i in c2:
        count = count+i.itemcount
    nc = notifi.objects.filter(owner_id=request.user.id)
    beats = work_info.objects.filter(user_id=request.user.id)
    veri = profile.objects.filter(user_id=request.user.id).values('verified', 'veri_submit')
    ff = work_info.objects.all().order_by('?')[:4]
    if( not veri[0]['verified']):
        if(not veri[0]['veri_submit']):
            messages.success(request, 'Please verifi your details to obtain the maximum of our services')
    return render(request, 'users/profile.html', {'beats': beats, 'count':count, 'ncount':nc.count(), 'fu':ff})

@login_required
def edit(request):
    count=0
    c2 = cart.objects.filter(user_id=request.user.id)
    nc = notifi.objects.filter(owner_id=request.user.id)
    ff = work_info.objects.all().order_by('?')[:4]
    for i in c2:
        count = count+i.itemcount
    if request.method=='POST':
        form1 = InfoUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if form1.is_valid():
            form1.save()
            return redirect('profile')
        else:
            messages.warning(request, 'Some errors in the input, please try again..')
            return redirect('profile')
    else:
        form = InfoUpdateForm(instance=request.user.profile)
        return render(request, 'users/editinfo.html', {'form': form, 'count':count, 'ncount':nc.count(), 'ff':ff})


def logout_view(request):
    logout(request)
    return redirect('login')

def galleryouter(request):
    return render(request, 'beats/gallery_outer.html')

@method_decorator(login_required, name='dispatch')
class UserDetailsView(DetailView):
    model = User
    template_name = 'users/infouser.html'
    context_object_name = 'user'
    def get_context_data(self, **kwargs):
        pk = self.kwargs.get('pk')
        context = super().get_context_data(**kwargs)
        context["beats"] = work_info.objects.filter(user_id=pk)
        count=0
        c2 = cart.objects.filter(user_id=self.request.user.id)
        nc = notifi.objects.filter(owner_id=self.request.user.id)
        for i in c2:
            count = count+i.itemcount
        context["count"] = count
        context['ncount'] = nc.count()
        return context

@login_required
def notif(request,pk):
    count=0
    c2 = cart.objects.filter(user_id=request.user.id)
    nc = notifi.objects.filter(owner_id=request.user.id)
    for i in c2:
        count = count+i.itemcount
    if request.method == 'POST':
        form = NotifyForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data.get('data')
            header1 = form.cleaned_data.get('hae')
            user = User.objects.filter(id=pk).first()
            beats = work_info.objects.filter(user_id=pk)
            noti = notifi(user_id=request.user.id, owner_id=user, header=header1, contect=data)
            noti.save()
            messages.add_message(request, messages.SUCCESS, 'Message Sent')
            return render(request, 'users/infouser.html', {'user':user,'beats':beats, 'count':count, 'ncount':nc.count()})
        else:
           messages.add_message(request, messages.WARNING, 'Error occuried, please try again later')
           user = User.objects.filter(id=pk).first()
           return render(request, 'users/infouser.html', {'user':user, 'count':count, 'ncount':nc.count()})
    else:
        messages.add_message(request, messages.ERROR, 'Error occuried, please try again later')
        user = User.objects.filter(id=pk).first()
        return render(request, 'users/infouser.html', {'user':user, 'count':count, 'ncount':nc.count()})

def helpinfofun(request):
    if request.method =="POST":
        form = helpform(request.POST)
        if form.is_valid():
            name = form.cleaned_data.get('name')
            email = form.cleaned_data.get('email')
            message = form.cleaned_data.get('message')
            hi = helpinfo(name=name, email=email, message=message)
            hi.save()
            messages.add_message(request, messages.SUCCESS, 'Message Sent')
            return render(request, 'beats/index.html')

        else:
            return render(request, 'beats/index.html')
    else:
        return render(request, 'beats/index.html')
@login_required
def verifi(request):
    count=0
    c2 = cart.objects.filter(user_id=request.user.id)
    for i in c2:
        count = count+i.itemcount
    nc = notifi.objects.filter(owner_id=request.user.id)
    if(not request.user.profile.veri_submit):
        if request.method=="POST":
            form = verifiform(request.POST)
            if form.is_valid():
                phone = form.cleaned_data.get('phone')
                email = form.cleaned_data.get('email')
                vtype = form.cleaned_data.get('vtype')
                vno = form.cleaned_data.get('vno')
                veri = verification(user_id=request.user.id, phone=phone, email=email, vtype=vtype, vno=vno)
                veri.save()
                request.user.profile.verichange()
                ff = work_info.objects.all().order_by('?')[:4]
                return render(request, 'users/verification_done.html', {'ff':ff})
            else:
                messages.add_message(request, messages.WARNING, 'Some error occuried during uploading your details, please try after some time.')
                form = verifiform()
                ff = work_info.objects.all().order_by('?')[:4]
                return render(request, 'users/verification.html', {'form':form, 'ncount':nc.count(), 'ff':ff, 'count':count })

        else:
            form = verifiform()
            ff = work_info.objects.all().order_by('?')[:4]
            return render(request, 'users/verification.html', {'form':form, 'ff':ff, 'ncount':nc.count(), 'count':count})
    else:
        ff = work_info.objects.all().order_by('?')[:4]
        return render(request, 'users/verification_done.html', {'ncount':nc.count(), 'ff':ff, 'count':count})

@login_required
def advice_view(request):
    count=0
    c2 = cart.objects.filter(user_id=request.user.id)
    for i in c2:
        count = count+i.itemcount
    nc = notifi.objects.filter(owner_id=request.user.id)
    if request.method=='POST':
        form = adviceform(request.POST)
        if form.is_valid():
            platform = form.cleaned_data.get('platform')
            content = form.cleaned_data.get('content')
            ad = advice(user_id=request.user.id, platform=platform, content=content)
            ad.save()
            ff = work_info.objects.all().order_by('?')[:4]
            messages.success(request, "Your request has been posted successfully, we will get back to you soon. Don't forget to check your notification box regulary. We will do our best to help you ")
            return render(request, 'users/advice.html', {'ncount':nc.count(), 'ff':ff, 'count':count})
        else:
            ff = work_info.objects.all().order_by('?')[:4]
            messages.warning(request, 'Some problem occuried while, uploading your form, please try again.')
            return render(request, 'users/advice.html', {'ncount':nc.count(), 'ff':ff, 'count':count})
    else:
        ff = work_info.objects.all().order_by('?')[:4]
        return render(request, 'users/advice.html', {'ncount':nc.count(), 'ff':ff, 'count':count})
@login_required
def deleteb(request, pk):
    work_info.objects.filter(Bid=pk).delete()
    count=0
    c2 = cart.objects.filter(user_id=request.user.id)
    for i in c2:
        count = count+i.itemcount
    nc = notifi.objects.filter(owner_id=request.user.id)
    beats = work_info.objects.filter(user_id=request.user.id)
    veri = profile.objects.filter(user_id=request.user.id).values('verified', 'veri_submit')
    if( not veri[0]['verified']):
        if(not veri[0]['veri_submit']):
            messages.success(request, 'Please verifi your details to obtain the maximum of our services')
    return render(request, 'users/profile.html', {'beats': beats, 'count':count, 'ncount':nc.count()})


@login_required
def editb(request, pk):
    count=0
    c2 = cart.objects.filter(user_id=request.user.id)
    nc = notifi.objects.filter(owner_id=request.user.id)
    ff = work_info.objects.all().order_by('?')[:4]

my-site/users/templates/users/advice.html
{% extends "users/verification.html" %}

{% load static %}

{% block title %}
    Advice
{% endblock title %}

{% block title2 %}
    Advice Corner
{% endblock title2 %}
{% block Main_Content %}
        <p style='text-align:center; font-size:1.3em; font-weight:700;'>We will do our best, to provide you the maximum profit.<br> Thank you for your trust</p>

    <form method="post" style='width:30em; margin-left:8em;' action='.'>
    {% csrf_token %}
    <label for="id_platform">Platform:</label><br>
    <select name="platform" style='width:10em;' id="id_platform">
    <option value="U" selected="">SilverChords</option>
    <option value="Y">Youtube</option>
    <option value="I">Instagram</option>
    <option value="F">Facebook</option>
    <option value="S">Snapchat</option></select><br>
    <br><label for="id_content">Content:</label>
    <p><textarea name="content" cols="60" rows="10" maxlength="1000" required="" id="id_content"></textarea></p><br>
    <input type="submit" class="" style="margin-left:400px; background-color:#007bff" value="Post">	
    </form>	
   

{% endblock Main_Content %}









										

my-site/users/templates/users/editinfo.html
{% extends "users/verification.html" %}

{% block title %}
    EDIT PERSONAL INFO
{% endblock title %}

{% block title2 %}
        Personal Info Edit
{% endblock title2 %}

{% block Main_Content %}
    <form action='.' method='POST' enctype="multipart/form-data">
    {% csrf_token %}
    <img alt='user image' src="{{user.profile.artist_photo.url}}" style='height:5em; width:5em;'>
    <label for='id_artist_photo' style='font-family:cursive; font-size:15px;'>Change Profile</label>
    <input type='file' name='artist_photo' accept='image/*' id='id_artist_photo'><br><br>

    <img alt='user cover' src="{{user.profile.cover_photo.url}}" style='height:5em; width:5em;'>
    <label for='id_cover_photo' style='font-family:cursive; font-size:15px;'>Change Cover</label>
    <input type='file' name='cover_photo' accept='image/*' id='id_cover_photo'><br><br>

    <label for='id_place' style='font-family:cursive; font-size:15px;'>Place</label>
    <input style='font-family:cursive;' class='form-control' type='text' name='place' value='{{user.profile.place}}' id='id_place'>

    <br><label for='id_desc' style='font-family:cursive; font-size:15px;'>About You</label>
    <p><textarea style='font-family:cursive;' class='form-control' name='desc' cols='40' rows='8' maxlength= '2000'required id='id_desc'>{{user.profile.desc}}</textarea></p>
    
    <br><label style='font-family:cursive; font-size:15px;' for='id_fb'>Facebook</label>
    <input style='font-family:cursive;' class='form-control' type='text' name='fb' value='{{user.profile.fb}}' id='id_fb'>
    
    <br><label style='font-family:cursive; font-size:15px;' for='id_insta'>Instagram</label>
    <input style='font-family:cursive;' class='form-control' type='text' name='insta' value='{{user.profile.insta}}' id='id_insta'>
    
    <br><label style='font-family:cursive;font-size:15px;' for='id_youtube'>Youtube</label>
    <input style='font-family:cursive;' class='form-control' type='text' name='youtube' value='{{user.profile.youtube}}' id='id_youtube'>
    
    <br><input style='font-family:cursive;' type='submit' value='Save'>
    </form>
{% endblock Main_Content %}

my-site/users/templates/users/register.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
<title>SilverChords</title>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <!-- Google Fonts -->
    
    <link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,200,300,700,600' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:400,700,300' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,100' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href='{% static 'boot/css/bootstrap.min.css' %}' type="text/css" />
	<link rel="stylesheet" href="{% static 'assets/css/font-awesome.min.css' %}">

	<link rel="stylesheet" href="{% static 'assets/css/owl.carousel.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'main1.css' %}" type="text/css">



</head>
<body>
    <div class="site-branding-area">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div class="logo">
                        <h1><a href=""><img src="/media/img/logo.png"></a></h1>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End site branding area -->


							
<section id="form" ><!--form-->
		<div class="container" >
			<div class="row">
				<div class="col-sm-4 col-sm-offset-1">
					<div class="login-form"><!--login form-->
<section id="wrapper" style=' width:80em;'>
						
							<div class="inner" style=" width:40%; padding:20px 20px 0px 20px; border: 2px solid white; border-radius: 25px;">
								<h2 class='text-center' style='font-size:40px;'><b>Login</b></h2><br>
								<div>
								{% if form.errors %}
									<p  class="alert alert-danger" role="alert">Your username and password didn't match. Please try again.</p>
									{% endif %}

									{% if next %}
										{% if user.is_authenticated %}
										<p  class="alert alert-danger" role="alert">Your account doesn't have access to this page. To proceed,
										please login with an account that has access.</p>
										{% else %}
										<p  class="alert alert-danger" role="alert">Please login to see this page.</p>
										{% endif %}
									{% endif %}
								</div>
									<form method='POST' action='{% url 'login' %}' class="form-signin">
											{% csrf_token %}
										<div class="form-label-group ">
											<label for="id_username">Username</label>
											<input type="text" id="id_username" name='username' class="form-control" placeholder="Username" required autofocus>
										</div>

										<div class="form-label-group ">
											<label for="id_password">Password</label>
											<input type="password" id="id_password" name='password' class="form-control" placeholder="Password" required>
										</div>
											<br>
										<div class="custom-control custom-checkbox mb-3">
											<input type="checkbox" class="custom-control-input" id="customCheck1">
											<label class="custom-control-label" for="customCheck1">Remember password</label>
										</div>
										<button class="btn btn-lg  btn-block text-uppercase button primary" type="submit">Sign in</button>
										
										
									</form>
								</div>
						
					</section>
					</div><!--/login form-->
				</div>
				<div class="col-sm-1" style='margin-left:10em;'>
					<h2 class="or">OR</h2>
				</div>
				<div class="col-sm-4">
					<div class="signup-form"><!--sign up form-->
							<section id="wrapper" >
						
							<div class="inner" >
								<h2 class='text-center' style='font-size:2.5em;margin-left:4em;'><b>Register</b></h2><br>
								<div>
										{% if messages %}
                                        {% for message in messages %}
                                            <p class="alert alert-danger" role="alert" style='text-align:center;'> {{ message }} </p>
                                        {% endfor %}
                                        {% endif %}
								</div>
									<form method='POST' style=' width:30em;' action='{% url 'register' %}' class="form-signin">
											       {% csrf_token %}
											<label for="id_username">Username:</label><br>
											<input type="text" name="username" maxlength="150" class="form-control" autofocus="" required="" id="id_username">
											
											<small style="color: grey">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</small>
											
										<p></p>
										
											<label for="id_password1">Password:</label><br>
											<input type="password" name="password1" class="form-control" required="" id="id_password1">
											
											<small style="color: grey"><ul><li>Your password can't be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can't be a commonly used password.</li><li>Your password can't be entirely numeric.</li></ul></small>
											
											
										<p></p>
										
											<label for="id_password2">Password confirmation:</label><br>
											<input type="password" name="password2" class="form-control" required="" id="id_password2">
											
											<small style="color: grey">Enter the same password as before, for verification.</small>
											
											
										<p></p>
											
										</p>
							<button class="btn btn-lg  btn-block text-uppercase button primary" type="submit">Register</button>
									</form>
								</div>
					</section>
					</div><!--/sign up form-->
				</div>
			</div>
		</div>
	</section><br><br>


    <div class="footer-top-area">
        <div class="zigzag-bottom"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-6">
                    <div class="footer-about-us">
                        <h2>u<span>SilverChords</span></h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perferendis sunt id doloribus vero quam laborum quas alias dolores blanditiis iusto consequatur, modi aliquid eveniet eligendi iure eaque ipsam iste, pariatur omnis sint! Suscipit, debitis, quisquam. Laborum commodi veritatis magni at?</p>
                        <div class="footer-social">
                            <a href="#" target="_blank"><i class="fa fa-facebook"></i></a>
                            <a href="#" target="_blank"><i class="fa fa-twitter"></i></a>
                            <a href="#" target="_blank"><i class="fa fa-youtube"></i></a>
                            <a href="#" target="_blank"><i class="fa fa-linkedin"></i></a>
                        </div>
                    </div>
                </div>
                
                <div class="col-md-3 col-sm-6">
                    <div class="footer-menu">
                        <h2 class="footer-wid-title">User Navigation </h2>
                        <ul>
                            <li><a href="#">My account</a></li>
                            <li><a href="#">Order history</a></li>
                            <li><a href="#">Logout</a></li>

                        </ul>                        
                    </div>
                </div>
                
                <div class="col-md-3 col-sm-6">
                    <div class="footer-menu">
                        <h2 class="footer-wid-title">Categories</h2>
                        <ul>
                            <li><a href="#">Mobile Phone</a></li>
                            <li><a href="#">Home accesseries</a></li>
                            <li><a href="#">LED TV</a></li>
                            <li><a href="#">Computer</a></li>
                            <li><a href="#">Gadets</a></li>
                        </ul>                        
                    </div>
                </div>
                
                <div class="col-md-3 col-sm-6">
                    <div class="footer-newsletter">
                        <h2 class="footer-wid-title">Newsletter</h2>
                        <p>Sign up to our newsletter and get exclusive deals you wont find anywhere else straight to your inbox!</p>
                        <div class="newsletter-form">
                            <form action="#">
                                <input type="email" placeholder="Type your email">
                                <input type="submit" value="Subscribe">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End footer top area -->
    
    <div class="footer-bottom-area">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div class="copyright">
                        <p>&copy; 2015 uCommerce. All Rights Reserved. <a href="http://www.freshdesignweb.com" target="_blank">freshDesignweb.com</a></p>
                    </div>
                </div>
                
                <div class="col-md-4">
                    <div class="footer-card-icon">
                        <i class="fa fa-cc-discover"></i>
                        <i class="fa fa-cc-mastercard"></i>
                        <i class="fa fa-cc-paypal"></i>
                        <i class="fa fa-cc-visa"></i>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End footer bottom area -->
   
    <!-- Latest jQuery form server -->
		<script src='{% static 'main.js' %}' type="text/javascript"></script>
    
    <!-- Bootstrap JS form CDN -->
		<script src='{% static 'boot/js/bootstrap.min.js' %}' type="text/javascript"></script>

    <!-- jQuery sticky menu -->
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.sticky.js' %}"></script>
    
    <!-- jQuery easing -->
    <script src="{% static 'js/jquery.easing.1.3.min.js' %}"></script>
    
    <!-- Main Script -->
    <script src="{% static 'js/main.js' %}"></script>
    
    <!-- Slider -->
    <script type="text/javascript" src="{% static 'js/bxslider.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/script.slider.js' %}"></script>

	<!--Play-->
	<script src='{% static 'play.js' %}' type="text/javascript"></script>
	
	<!--Cart-->
	<script src='{% static 'cart.js' %}' type="text/javascript"></script>

  </body>
</html>

my-site/users/templates/users/verification_done.html
{% extends "users/verification.html" %}

{% load static %}

{% block title %}
Verification Details
{% endblock title %}

{% block title2 %}
Verification Details
{% endblock title2 %}

{% block Main_Content %}
<p style='font-size:2em; text-align:center;'> We are verifying your details. Thank You for your cooperation</p> 
{% endblock Main_Content %}