my-site/beats/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from beats import views 


urlpatterns = [
    path('home/', views.home, name='home'),
    path('gallery/', views.gallery, name='gallery'),
    path('upload/', views.upload, name='upload'),
    path('history/', views.HistoryNameList.as_view(), name='history'),
    path('beat/<int:pk>/', views.beatdetails, name='beat-details'),
    path('cart/', views.beatcart, name='cart'),
    path('bought/', views.bbought, name='bought'),
    path('buyandcart/<int:pk>/', views.cartbuy, name='buycart'),
    path('cartdetails/', views.cartdetails, name='detailcart'),
    path('cartdelete/<int:pk>', views.cartdelete, name='deletecart'),
    path('listens/<int:pk>', views.listensupdate, name='listensupdate'),
    path('play/', views.playsonng, name='playsong'),
    path('histdetail/<int:pk>', views.historydetail, name='historydetail'),
    path('search/', views.search,name='search'),
    path('beatlist/', views.BeatListView.as_view(), name='beat-list'), 
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my-site/silverchords/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from users import views as users_views
from beats import views as beats_views
from notifis import views as noti_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('galleryouter/', users_views.galleryouter, name='gallery2'),
    path('beats/', include('beats.urls')),
    path('users/', include('users.urls')),
    path('SilverChords/',beats_views.home, name='silverchords'),
    path('help/', users_views.helpinfofun, name='helpinfo'),
    path('notifications/list', include('notifis.urls')),   
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

my-site/beats/models.py
from django.db import models
from django.contrib.auth.models import User
from rest_framework import serializers

class work_info(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    Bid = models.AutoField(primary_key=True)
    producer = models.CharField(max_length=100)
    beat_name = models.CharField(max_length=100)
    beat = models.FileField(upload_to='beats')
    genre = models.CharField(max_length=30,default='R',choices=[
        ('R','Rock'),
        ('E','Electric'),
        ('Hh','Hip Hop'),
        ('C','Country'),
        ('t', 'Techno/trance'),
        ('Db', 'Drum And Bass'),
        ])
    beat_img = models.ImageField(upload_to='beat_img')
    beat_desc = models.TextField(max_length=2000)
    beat_date = models.DateTimeField(auto_now_add=True)
    price = models.PositiveIntegerField(default=0)
    listens = models.IntegerField(default=0)

    def editp(self, var1):
        self.price = var1
        self.save()

    def editn(self, var1):
        self.beat_name = var1
        self.save()

    def editd(self, var1):
        self.beat_desc = var1
        self.save()
    
    def editg(self, var1):
        self.genre = var1
        self.save()

    def __str__(self):
        return self.beat_name
    
    def listens_update(self):
        self.listens=self.listens+1
        self.save()
        

class reviews(models.Model):
    review_id = models.AutoField(primary_key=True)
    Bid = models.ForeignKey(work_info, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.PositiveSmallIntegerField(default=5,choices=[
        (1,'Poor'),
        (2,'Ok Ok'),
        (3,'Average'),
        (4,'Great'),
        (5, 'Blast'),
        ])
    comment = models.TextField(max_length=2000)

    def __str__(self):
        return f'{self.user.username} review for {self.Bid.beat_name}'

class Userhistory(models.Model):
    h_id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    Bid = models.ForeignKey(work_info, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.username} {self.Bid.beat_name}'

    def retBid(self):
        return f'{self.Bid.Bid}'

class cart(models.Model):
    cid =models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    Bid = models.ForeignKey(work_info, on_delete=models.CASCADE)
    price = models.PositiveIntegerField(default=0)
    itemcount = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f'{self.user.username} cart has {self.Bid.beat_name} {self.itemcount}'

    def coutninc(self, v1):
        self.itemcount = self.itemcount+v1
        self.save()  

class bought(models.Model):
    bbid = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    b_name = models.CharField(max_length=100)
    b_img = models.ImageField(upload_to='bb_img')

    def __str__(self):
        return f'{self.user.username} bought {self.b_name}'

my-site/beats/forms.py
from django import forms
from .models import work_info, reviews


class beatupload(forms.ModelForm):
    class Meta:
        model = work_info
        fields = ['beat_name', 'beat', 'genre', 'beat_img', 'beat_desc', 'price']

class searchform(forms.Form):
    search_token = forms.CharField(max_length=100, label='search_token')

class reviewsform(forms.ModelForm):
    class Meta:
        model = reviews
        fields = ['rating', 'comment']

my-site/beats/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from .forms import beatupload, searchform, reviewsform
from .models import work_info, reviews, Userhistory, cart, bought
from users.models import quote, profile, verification
from django import forms
from django.views.generic import ListView, DetailView
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from notifis.models import notifi


def home(request):
    count=0
    c2 = cart.objects.filter(user_id=request.user.id)
    nc = notifi.objects.filter(owner_id=request.user.id)
    for i in c2:
        count = count+i.itemcount
        ################################
    mt = work_info.objects.all().order_by('-listens')[:10]
    ff = work_info.objects.all().order_by('-beat_date')[:10]
    if request.user.is_authenticated:
        ver = profile.objects.filter(user_id=request.user.id).values('verified', 'veri_submit')
        if( not ver[0]['verified']):
            if(not ver[0]['veri_submit']):
                messages.warning(request, 'Please verifi your details to obtain the maximum of our services')
    return render(request, 'beats/index.html', {'count':count, 'ncount':nc.count(), 'mt':mt, 'ff':ff})



def silverchords(request):
    return render(request, 'beats/index.html')


def gallery(request):
    count=0
    c2 = cart.objects.filter(user_id=request.user.id)
    nc = notifi.objects.filter(owner_id=request.user.id)
    for i in c2:
        count = count+i.itemcount
    return render(request, 'beats/gallery.html', {'count':count, 'ncount':nc.count()})


@login_required
def search(request):
    count=0
    c2 = cart.objects.filter(user_id=request.user.id)
    nc = notifi.objects.filter(owner_id=request.user.id)
    for i in c2:
        count = count+i.itemcount
    if request.method=='POST':
        form = searchform(request.POST)
        if form.is_valid():
            search = form.cleaned_data.get('search_token')
            work = work_info.objects.filter(beat_name__contains=search)
            genres = work_info.objects.filter(genre__contains=search)
            user = User.objects.filter(username__contains=search)
            count=0
            c2 = cart.objects.filter(user_id=request.user.id)
            for i in c2:
                count = count+i.itemcount
            return render(request, 'beats/search.html', {'work':work, 'genres':genres, 'users':user, 'name':search, 'count':count, 'ncount':nc.count()})
        quotea=quote.objects.order_by("?").first()
        return render(request, 'beats/index.html.', {'quote':quotea, 'count':count, 'ncount':nc.count()})
    else:
        quotea=quote.objects.order_by("?").first()
        return render(request, 'beats/index.html.', {'quote':quotea, 'count':count, 'ncount':nc.count()})

@login_required
def listensupdate(request,pk):
    query = work_info.objects.filter(Bid=pk)
    query.listens_update()
    
@login_required
def playsonng(request):
    if request.method =='POST':
        id = request.POST.get('Bid')
        work = work_info.objects.filter(Bid = id)
        work[0].listens_update()
        his1 = Userhistory.objects.filter(user_id=request.user.id, Bid=id)
        if (his1.count()==0):
            his2 = Userhistory.objects.filter(user_id=request.user.id)
            if (his2.count()<10):
                us = Userhistory(user_id=request.user.id, Bid=work[0])
                us.save()
            else:
                did=his2[0].retBid()
                Userhistory.objects.filter(user_id=request.user.id, Bid=did).delete()
                us1 = Userhistory(user_id=request.user.id, Bid=work[0])
                us1.save()
        return HttpResponse("Success")
    else:
        return HttpResponse("Failure")

@login_required
def historydetail(request,pk):
    count=0
    c2 = cart.objects.filter(user_id=request.user.id)
    nc = notifi.objects.filter(owner_id=request.user.id)
    for i in c2:
        count = count+i.itemcount
    work = work_info.objects.filter(Bid = pk).order_by('-h_id')
    return render(request, 'beats/beatdetails.html', {'beat':work[0], 'count':count, 'ncount':nc.count()})

@login_required
def upload(request):
    if request.method=='POST':
        form1 = beatupload(request.POST, request.FILES)
        if form1.is_valid():
            user1 = form1.save(commit=False)
            user1.user_id = request.user.id
            user1.producer = request.user.username
            user1.save()
            messages.warning(request, 'Work Uploaded Successfully :)')
            return redirect('silverchords')
        else:
            count=0
            c2 = cart.objects.filter(user_id=request.user.id)
            nc = notifi.objects.filter(owner_id=request.user.id)
            for i in c2:
                count = count+i.itemcount
            messages.warning(request, 'Not a valid input, please try again..')
            ff = work_info.objects.all().order_by('?')[:4]
            return render(request, 'beats/upload.html', {'ff':ff, 'count':count, 'ncount':nc.count()})
    else:
        count=0
        c2 = cart.objects.filter(user_id=request.user.id)
        nc = notifi.objects.filter(owner_id=request.user.id)
        ff = work_info.objects.all().order_by('?')[:4]
        for i in c2:
            count = count+i.itemcount
        form1 = beatupload()
        return render(request, 'beats/upload.html', {'ff':ff, 'count':count, 'ncount':nc.count(), 'form':form1})

@method_decorator(login_required, name='dispatch')
class BeatListView(ListView):
    model = work_info
    template_name = 'beats/beatlist.html'
    #queryset = work_info.objects.filter(genre='rock')
    context_object_name = 'beats'
    ordering = ['-beat_date']
    paginate_by = 3

@method_decorator(login_required, name='dispatch')
class HistoryNameList(ListView):
    model = Userhistory
    #context_object_name = 'historys'
    template_name='beats/history.html'
    def get_context_data(self, **kwargs):
        #context = super().get_context_data(**kwargs)
        con = Userhistory.objects.filter(user_id=self.request.user.id).order_by('-h_id')
        count=0
        c2 = cart.objects.filter(user_id=self.request.user.id)
        nc = notifi.objects.filter(owner_id=self.request.user.id)
        ff = work_info.objects.all().order_by('?')[:4]
        for i in c2:
            count = count+i.itemcount
        context = {
        
            'historys':con,
            'ff':ff,
            'count':count,
            'ncount':nc.count()
        }
        return context

@login_required
def beatdetails(request, pk):
    count=0
    c2 = cart.objects.filter(user_id=request.user.id)
    nc = notifi.objects.filter(owner_id=request.user.id)
    for i in c2:
        count = count+i.itemcount
    if request.method=='POST':
        form = reviewsform(request.POST)
        if form.is_valid():
            rate = form.cleaned_data.get('rating')
            cmnt = form.cleaned_data.get('comment')
            us = work_info.objects.filter(Bid=pk)
            riv = reviews(Bid=us[0], user_id=request.user.id, rating=rate, comment=cmnt)
            riv.save()
            messages.success(request, 'Your review is succesfully posted!!!')
            rev = reviews.objects.filter(Bid=pk).order_by('-review_id')
            beat = work_info.objects.filter(Bid=pk)
            form1 = reviewsform()
            g = beat[0].genre
            fu = work_info.objects.filter(genre=g).exclude(Bid=pk).order_by('?')[:4]
            print(fu)
            return render(request, 'beats/beatdetails.html', {'reviews':rev, 'beat':beat[0], 'form':form1, 'fu':fu, 'count':count, 'ncount':nc.count()})
        else:
            messages.warning(request, 'Some Error occuried while posting your review, please try again later.')
            rev = reviews.objects.filter(Bid=pk).order_by('-review_id')
            beat = work_info.objects.filter(Bid=pk)
            form1 = reviewsform()
            g = beat[0].genre
            fu = work_info.objects.filter(genre=g).exclude(Bid=pk).order_by('?')[:4]
            return render(request, 'beats/beatdetails.html', {'reviews':rev, 'n':range(1, rev[0].rating), 'fu':fu, 'beat':beat[0], 'form':form1, 'count':count, 'ncount':nc.count()})
    else:
        rev = reviews.objects.filter(Bid=pk).order_by('-review_id')
        beat = work_info.objects.filter(Bid=pk)
        form1 = reviewsform()
        g = beat[0].genre
        fu = work_info.objects.filter(genre=g).exclude(Bid=pk).order_by('?')[:4]
        return render(request, 'beats/beatdetails.html', {'reviews':rev,'fu':fu, 'beat':beat[0], 'form':form1, 'count':count, 'ncount':nc.count()})

    
@login_required
def beatcart(request):
    if request.method =='POST':
        id = request.POST.get('Bid')
        q = int(request.POST.get('quantity'))
        w = work_info.objects.filter(Bid=id)
        p = w[0].price
        c1 = cart.objects.filter(user_id=request.user.id, Bid=id)
        if(c1.count()>0):
            c1[0].coutninc(q)
        else:
            c =cart(user_id=request.user.id, Bid=w[0], price=p)
            c.coutninc(q)
            c.save()
        count=0
        c2 = cart.objects.filter(user_id=request.user.id)
        for i in c2:
            count = count+i.itemcount
        return HttpResponse(str(count))
    else:
        return HttpResponse('Failure')


@login_required
def cartdetails(request):
    count=0
    final=0
    c2 = cart.objects.filter(user_id=request.user.id)
    nc = notifi.objects.filter(owner_id=request.user.id)
    for i in c2:
        count = count+i.itemcount
        final = final+((i.price)*(i.itemcount))
    if c2.count()==0:
        fu = work_info.objects.filter(genre='rock').order_by('?')[:4]
        print(fu)
        return render(request, 'beats/cart.html', {'beats':c2, 'count':count, 'ncount':nc.count(), 'final':final, 'fu':fu})
    else:
        g = c2[0].Bid.genre

my-site/beats/templates/beats/bbought.html
{% extends "users/verification.html" %}

{% block title %}
    Beats Bought
{% endblock title %}

{% block title2 %}
        Buying History
{% endblock title2 %}

{% block Main_Content %}
    
{% if beats.count %}
    <div class="maincontent-area">
        <div class="zigzag-bottom"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="latest-product">
                        <div class="product-carousel" style='width:55em;'>						
							{% for beat in beats  %}
                            <div class="single-product">
                                <div class="product-f-image">
                                    <img src="{{beat.b_img.url}}" style='height:16em; ' alt="">
                                </div>
                                <h2><a href="" style='text-decoration:none;'>{{beat.b_name}}</a></h2>
                                
                                <div class="product-carousel-price">
                                    <ins><i class="fa fa-download" style="font-size:0.8em; "></i><a href='' style="font-size:0.8em;"> Download Agreement</a></ins><br>
                                </div> 
                            </div>
							{% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endif %}
{% endblock Main_Content %}

my-site/beats/templates/beats/editbeatinfo.html
{% extends "users/verification.html" %}

{% block title %}
    Edit Beat
{% endblock title %}

{% block title2 %}
        Beat Info Edit
{% endblock title2 %}

{% block Main_Content %}
    <h2 class='pb-1' style='text-align: center; font-family:cursive; font-size: 2.5em;'>Edit Beat Info</h2><br>
    <form action='{% url 'editbeat' Bid  %}' method='POST' enctype="multipart/form-data" >
    {% csrf_token %}
        <label for="id_beat_name">Beat name:</label>
        <input type="text" class='form-control' name="beat_name" value="Baggi intro" maxlength="100" required="" id="id_beat_name">
        <br><label for="id_genre">Genre:</label>
        <select class='form-control' name="genre" style='width:300px;' id="id_genre">
        <option value="R">Rock</option>
        <option value="E">Electric</option>
        <option value="Hh">Hip Hop</option>
        <option value="C">Country</option>
        <option value="t">Techno/trance</option>
        <option value="Db">Drum And Bass</option>
        </select>
        <br><label for="id_beat_desc">Beat desc:</label>
        <p><textarea class='form-control' name="beat_desc" cols="40" rows="5" maxlength="2000" required="" id="id_beat_desc">dhkdadqwhdqwdq</textarea></p>
        <label for="id_price" >Price:</label>
        <input class='form-control' type="text" name="price" required="" value='&#x20b9; {{price}}' style='width:300px;' id="id_price">
   <br> <input type='submit' style=' margin-left:20em; background-color:#007bff' value='Upload'>
    </form>
{% endblock Main_Content %}

my-site/beats/templates/beats/gallery.html
{% extends "beats/base.html" %}
{% load static %}

{% block title %}
    Gallery
{% endblock title %}

{% block Main_Content %}
    <p class='' style=' margin-left:300px; font-family:cursive; font-size: 2em;'>We Are working on this page developement. :)</p>
{% endblock Main_Content %}

my-site/beats/templates/beats/history.html
{% extends "users/verification.html" %}

{% load static %}

{% block title2 %}
History
{% endblock title2 %}

{% block title %}
    SilverChords history
{% endblock title %}

{% block Main_Content %}
    <div class="maincontent-area">
        <div class="zigzag-bottom"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="latest-product">
                        <div class="product-carousel" style='width:55em;'>						
							{% for beat in historys %}
                            <div class="single-product">
                                <div class="product-f-image">
                                    <img src="{{beat.Bid.beat_img.url}}" style='height:16em; width:15em;' alt="">
                                    <div class="product-hover">
                                        <a style='margin-top:1em;' onclick="play('{{beat.Bid.beat.url}}', '{{beat.Bid.beat_name}}', '{{beat.Bid.beat_img.url}}', '{{beat.Bid.Bid}}','{% url 'playsong' %}')" class="add-to-cart-link" ><i class="fa fa-play"></i>Play</a>
                                    </div>
                                </div>                                
                                <h2><a style='text-decoration:none;' href="{% url 'beat-details' beat.Bid.Bid %}">{{beat.Bid.beat_name}}</a></h2>
                                <div class="product-carousel-price">
                                    <ins>${{beat.Bid.price}}</ins> <del>$100.00</del>
                                </div> 
                            </div>
							{% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock Main_Content %}

my-site/beats/templates/beats/upload.html
{% extends "users/verification.html" %}

{% load static %}

{% block title2 %}
Upload
{% endblock title2 %}

{% block title %}
    SilverChords Upload
{% endblock title %}

{% block Main_Content %}
    <form method="post" style='width:30em; margin-left:8em;' action='.' enctype="multipart/form-data">
    {% csrf_token %}
        <label for="id_beat_name">Beat name:</label>
        <input type="text" class="form-control" name="beat_name" maxlength="100" required="" id="id_beat_name">
        <br><label for="id_beat">Beat:</label>
        <br><input  type="file" name="beat" accept='audio/*' required="" id="id_beat">
        <br><br><label for="id_genre">Genre:</label>
        <select class="form-control" style='width:300px;' name="genre" id="id_genre">
        <option value="R" selected="">Rock</option>
        <option value="E">Electric</option>
        <option value="Hh">Hip Hop</option>
        <option value="C">Country</option>
        <option value="t">Techno/trance</option>
        <option value="Db">Drum And Bass</option>
        </select>
        <br><label for="id_beat_img">Beat image:</label>
        <br><input type="file" accept='image/*' name="beat_img" accept="image/*" required="" id="id_beat_img">
        <br><br><label for="id_beat_desc">What you want to say about your creation??</label>
        <p><textarea class="form-control" name="beat_desc" cols="40" rows="5" maxlength="2000" required="" id="id_beat_desc" spellcheck="false"></textarea></p>
       <br><label for="id_price">Price:</label>
       <input class='form-control' type="text" style='width:300px;' name="price" min="0" palceholder='$$$$' required id="id_price">
   <br> <br><input style='margin-left:12em;' type='submit' value='Upload'>
    </form>
{% endblock Main_Content %}